### ISSUE TITLE
eventsFragment cannot be converted to a Fragment, using Roboguice

### ISSUE THREAD

**Issue by agb46** [roboguice/roboguice#280]
0 down vote favorite
	

I have the next issue with Fragments, Error:(120, 20) error: incompatible types: EventosFragment cannot be converted to Fragment. The code I used in the past without problems, with roboguice 3.0 and android support v4 r18,but now I have that problem. Now I'm working with roboguice 3.0.1 and support v4 r21.

I know that this thread just was write about it, but I don't see my solution.

I created a variable type Fragment (android.app.Fragment) cause my other Fragments like EventosFragment extends to RoboFragment (which extends ro Fragment - android.app.Fragment) but AndroidStudio show me the following message: Incompatible types.

It's about change the Fragment depending the clicking option in a listener. It should work because both Fragments extends the same type of Fragment(android.app.Fragment). I know that i could use supportFragment but both extend the same.

This is my code:

import android.app.Fragment;

@ContentView(R.layout.activity_main)
public class MainActivity extends RoboActivity {

private Fragment newFragment;
mDrawerList.setOnItemClickListener(new OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            posChecked = position;

            selection = position;
            newFragment = new Fragment();
            switch (position) {
            case Constantes.EVENTOS:
                newFragment = new EventosFragment();
                break;
            case Constantes.FERIAS_COMERCIALES:
                newFragment = new FeriasComercialesFragment();
                break;
            case Constantes.MONUMENTOS:
                newFragment = new MonumentosFragment();
                break;
            }
}
    });
if (savedInstanceState == null) {
        getFragmentManager().beginTransaction().setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).replace(R.id.content_frame, new BienvenidaFragment()).commit();
    }

	

I have the next issue with Fragments, Error:(120, 20) error: incompatible types: EventosFragment cannot be converted to Fragment. The code I used in the past without problems, with roboguice 3.0 and android support v4 r18,but now I have that problem. Now I'm working with roboguice 3.0.1 and support v4 r21.

I know that this thread just was write about it, but I don't see my solution.

I created a variable type Fragment (android.app.Fragment) cause my other Fragments like EventosFragment extends to RoboFragment (which extends ro Fragment - android.app.Fragment) but AndroidStudio show me the following message: Incompatible types.

It's about change the Fragment depending the clicking option in a listener. It should work because both Fragments extends the same type of Fragment(android.app.Fragment). I know that i could use supportFragment but both extend the same.

This is my code:

import android.app.Fragment;

@ContentView(R.layout.activity_main)
public class MainActivity extends RoboActivity {

private Fragment newFragment;
mDrawerList.setOnItemClickListener(new OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            posChecked = position;

            selection = position;
            newFragment = new Fragment();
            switch (position) {
            case Constantes.EVENTOS:
                newFragment = new EventosFragment();
                break;
            case Constantes.FERIAS_COMERCIALES:
                newFragment = new FeriasComercialesFragment();
                break;
            case Constantes.MONUMENTOS:
                newFragment = new MonumentosFragment();
                break;
            }
}
    });
if (savedInstanceState == null) {
        getFragmentManager().beginTransaction().setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).replace(R.id.content_frame, new BienvenidaFragment()).commit();
    }

And I get the following errors with Android Studio:

/Users/Alfonso/AndroidStudioProjects/CyLCultural/app/src/main/java/cylcultural/agb/es/cylcultural/activities/MainActivity.java:120: error: incompatible types: EventosFragment cannot be converted to Fragment newFragment = new EventosFragment(); ^ /Users/Alfonso/AndroidStudioProjects/CyLCultural/app/src/main/java/cylcultural/agb/es/cylcultural/activities/MainActivity.java:123: error: incompatible types: FeriasComercialesFragment cannot be converted to Fragment newFragment = new FeriasComercialesFragment(); ^

/Users/Alfonso/AndroidStudioProjects/CyLCultural/app/src/main/java/cylcultural/agb/es/cylcultural/activities/MainActivity.java:158: error: incompatible types: BienvenidaFragment cannot be converted to Fragment getFragmentManager().beginTransaction().setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).replace(R.id.content_frame, new BienvenidaFragment()).commit();

I don't know how resolved so I'm thankful if someone explain how I have to do it for resolved. I use Android.suport.v4 r21 and Roboguice 3.0.1 and Roboblender 3.0.1

Thanks in advance!!

**Comment by stephanenicolas** [comment]
Sorry, this is not readable. Format properly before re-opening.
